services:
  devto-mcp:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ./server.py:/app/server.py
    restart: unless-stopped
