services:
  devto-mcp:
    build: .
    ports:
      - "${PORT}:${PORT}"
      - "${REST_PORT:-8001}:8001"
    env_file:
      - .env
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ./server.py:/app/server.py
    restart: unless-stopped
